# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7z020clg400-2

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Users/Epoch/Desktop/FPGA_CNN_IP/FPGA_CNN_IP/FPGA_CNN_IP.cache/wt [current_project]
set_property parent.project_path C:/Users/Epoch/Desktop/FPGA_CNN_IP/FPGA_CNN_IP/FPGA_CNN_IP.xpr [current_project]
set_property XPM_LIBRARIES XPM_MEMORY [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo c:/Users/Epoch/Desktop/FPGA_CNN_IP/FPGA_CNN_IP/FPGA_CNN_IP.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files C:/Users/Epoch/Desktop/cnn_ip/cnn_ip/src/conv1_weight1_1.coe
add_files C:/Users/Epoch/Desktop/cnn_ip/cnn_ip/src/conv1_weight1_2.coe
add_files C:/Users/Epoch/Desktop/cnn_ip/cnn_ip/src/conv1_weight1_3.coe
add_files C:/Users/Epoch/Desktop/cnn_ip/cnn_ip/src/conv1_weight1_4.coe
add_files C:/Users/Epoch/Desktop/cnn_ip/cnn_ip/src/conv1_weight1_5.coe
add_files C:/Users/Epoch/Desktop/cnn_ip/cnn_ip/src/conv1_weight1_6.coe
add_files C:/Users/Epoch/Desktop/FPGA_CNN_IP/FPGA_CNN_IP/FPGA_CNN_IP.srcs/sources_1/ip/conv1_bias1_1.coe
add_files C:/Users/Epoch/Desktop/cnn_ip/cnn_ip/src/conv1_bias1_4.coe
add_files C:/Users/Epoch/Desktop/cnn_ip/cnn_ip/src/fc_weight1.coe
add_files C:/Users/Epoch/Desktop/cnn_ip/cnn_ip/src/conv2_weight2_1.coe
add_files C:/Users/Epoch/Desktop/cnn_ip/cnn_ip/src/conv1_bias1_2.coe
add_files C:/Users/Epoch/Desktop/cnn_ip/cnn_ip/src/conv2_weight2_4.coe
add_files C:/Users/Epoch/Desktop/cnn_ip/cnn_ip/src/conv2_weight2_5.coe
add_files C:/Users/Epoch/Desktop/cnn_ip/cnn_ip/src/conv1_bias1_3.coe
add_files C:/Users/Epoch/Desktop/cnn_ip/cnn_ip/src/conv1_bias1_6.coe
add_files C:/Users/Epoch/Desktop/cnn_ip/cnn_ip/src/conv2_weight2_3.coe
add_files C:/Users/Epoch/Desktop/cnn_ip/cnn_ip/src/conv2_weight2_6.coe
add_files C:/Users/Epoch/Desktop/cnn_ip/cnn_ip/src/conv1_bias1_5.coe
add_files C:/Users/Epoch/Desktop/FPGA_CNN_IP/FPGA_CNN_IP/FPGA_CNN_IP.srcs/sources_1/ip/conv2_weight2_2.coe
add_files C:/Users/Epoch/Desktop/cnn_ip/cnn_ip/src/image9.coe
add_files c:/Users/Epoch/Desktop/cnn_ip/cnn_ip/src/conv1_bias1_1.coe
read_verilog -library xil_defaultlib {
  C:/Users/Epoch/Desktop/FPGA_CNN_IP/FPGA_CNN_IP/FPGA_CNN_IP.srcs/sources_1/imports/src/conv.v
  C:/Users/Epoch/Desktop/FPGA_CNN_IP/FPGA_CNN_IP/FPGA_CNN_IP.srcs/sources_1/imports/src/maxpooling.v
  C:/Users/Epoch/Desktop/FPGA_CNN_IP/FPGA_CNN_IP/FPGA_CNN_IP.srcs/sources_1/imports/src/maxpooling2.v
  C:/Users/Epoch/Desktop/FPGA_CNN_IP/FPGA_CNN_IP/FPGA_CNN_IP.srcs/sources_1/imports/src/multiplier.v
  C:/Users/Epoch/Desktop/FPGA_CNN_IP/FPGA_CNN_IP/FPGA_CNN_IP.srcs/sources_1/imports/src/multiply.v
  C:/Users/Epoch/Desktop/FPGA_CNN_IP/FPGA_CNN_IP/FPGA_CNN_IP.srcs/sources_1/imports/src/result.v
  C:/Users/Epoch/Desktop/FPGA_CNN_IP/FPGA_CNN_IP/FPGA_CNN_IP.srcs/sources_1/imports/src/cnn_struct.v
}
read_ip -quiet C:/Users/Epoch/Desktop/FPGA_CNN_IP/FPGA_CNN_IP/FPGA_CNN_IP.srcs/sources_1/ip/weight_fc/weight_fc.xci
set_property used_in_implementation false [get_files -all c:/Users/Epoch/Desktop/FPGA_CNN_IP/FPGA_CNN_IP/FPGA_CNN_IP.srcs/sources_1/ip/weight_fc/weight_fc_ooc.xdc]

read_ip -quiet C:/Users/Epoch/Desktop/FPGA_CNN_IP/FPGA_CNN_IP/FPGA_CNN_IP.srcs/sources_1/ip/shift_ram_12/shift_ram_12.xci

read_ip -quiet C:/Users/Epoch/Desktop/FPGA_CNN_IP/FPGA_CNN_IP/FPGA_CNN_IP.srcs/sources_1/ip/shift_ram_28/shift_ram_28.xci

read_ip -quiet C:/Users/Epoch/Desktop/FPGA_CNN_IP/FPGA_CNN_IP/FPGA_CNN_IP.srcs/sources_1/ip/conv2_weight6/conv2_weight6.xci
set_property used_in_implementation false [get_files -all c:/Users/Epoch/Desktop/FPGA_CNN_IP/FPGA_CNN_IP/FPGA_CNN_IP.srcs/sources_1/ip/conv2_weight6/conv2_weight6_ooc.xdc]

read_ip -quiet C:/Users/Epoch/Desktop/FPGA_CNN_IP/FPGA_CNN_IP/FPGA_CNN_IP.srcs/sources_1/ip/conv2_weight5/conv2_weight5.xci
set_property used_in_implementation false [get_files -all c:/Users/Epoch/Desktop/FPGA_CNN_IP/FPGA_CNN_IP/FPGA_CNN_IP.srcs/sources_1/ip/conv2_weight5/conv2_weight5_ooc.xdc]

read_ip -quiet C:/Users/Epoch/Desktop/FPGA_CNN_IP/FPGA_CNN_IP/FPGA_CNN_IP.srcs/sources_1/ip/conv2_weight4/conv2_weight4.xci
set_property used_in_implementation false [get_files -all c:/Users/Epoch/Desktop/FPGA_CNN_IP/FPGA_CNN_IP/FPGA_CNN_IP.srcs/sources_1/ip/conv2_weight4/conv2_weight4_ooc.xdc]

read_ip -quiet C:/Users/Epoch/Desktop/FPGA_CNN_IP/FPGA_CNN_IP/FPGA_CNN_IP.srcs/sources_1/ip/conv2_weight3/conv2_weight3.xci
set_property used_in_implementation false [get_files -all c:/Users/Epoch/Desktop/FPGA_CNN_IP/FPGA_CNN_IP/FPGA_CNN_IP.srcs/sources_1/ip/conv2_weight3/conv2_weight3_ooc.xdc]

read_ip -quiet C:/Users/Epoch/Desktop/FPGA_CNN_IP/FPGA_CNN_IP/FPGA_CNN_IP.srcs/sources_1/ip/conv2_weight2/conv2_weight2.xci
set_property used_in_implementation false [get_files -all c:/Users/Epoch/Desktop/FPGA_CNN_IP/FPGA_CNN_IP/FPGA_CNN_IP.srcs/sources_1/ip/conv2_weight2/conv2_weight2_ooc.xdc]

read_ip -quiet C:/Users/Epoch/Desktop/FPGA_CNN_IP/FPGA_CNN_IP/FPGA_CNN_IP.srcs/sources_1/ip/conv2_weight1/conv2_weight1.xci
set_property used_in_implementation false [get_files -all c:/Users/Epoch/Desktop/FPGA_CNN_IP/FPGA_CNN_IP/FPGA_CNN_IP.srcs/sources_1/ip/conv2_weight1/conv2_weight1_ooc.xdc]

read_ip -quiet C:/Users/Epoch/Desktop/FPGA_CNN_IP/FPGA_CNN_IP/FPGA_CNN_IP.srcs/sources_1/ip/conv1_bias6/conv1_bias6.xci
set_property used_in_implementation false [get_files -all c:/Users/Epoch/Desktop/FPGA_CNN_IP/FPGA_CNN_IP/FPGA_CNN_IP.srcs/sources_1/ip/conv1_bias6/conv1_bias6_ooc.xdc]

read_ip -quiet C:/Users/Epoch/Desktop/FPGA_CNN_IP/FPGA_CNN_IP/FPGA_CNN_IP.srcs/sources_1/ip/conv1_bias5/conv1_bias5.xci
set_property used_in_implementation false [get_files -all c:/Users/Epoch/Desktop/FPGA_CNN_IP/FPGA_CNN_IP/FPGA_CNN_IP.srcs/sources_1/ip/conv1_bias5/conv1_bias5_ooc.xdc]

read_ip -quiet C:/Users/Epoch/Desktop/FPGA_CNN_IP/FPGA_CNN_IP/FPGA_CNN_IP.srcs/sources_1/ip/conv1_bias4/conv1_bias4.xci
set_property used_in_implementation false [get_files -all c:/Users/Epoch/Desktop/FPGA_CNN_IP/FPGA_CNN_IP/FPGA_CNN_IP.srcs/sources_1/ip/conv1_bias4/conv1_bias4_ooc.xdc]

read_ip -quiet C:/Users/Epoch/Desktop/FPGA_CNN_IP/FPGA_CNN_IP/FPGA_CNN_IP.srcs/sources_1/ip/conv1_bias3/conv1_bias3.xci
set_property used_in_implementation false [get_files -all c:/Users/Epoch/Desktop/FPGA_CNN_IP/FPGA_CNN_IP/FPGA_CNN_IP.srcs/sources_1/ip/conv1_bias3/conv1_bias3_ooc.xdc]

read_ip -quiet C:/Users/Epoch/Desktop/FPGA_CNN_IP/FPGA_CNN_IP/FPGA_CNN_IP.srcs/sources_1/ip/conv1_bias2/conv1_bias2.xci
set_property used_in_implementation false [get_files -all c:/Users/Epoch/Desktop/FPGA_CNN_IP/FPGA_CNN_IP/FPGA_CNN_IP.srcs/sources_1/ip/conv1_bias2/conv1_bias2_ooc.xdc]

read_ip -quiet C:/Users/Epoch/Desktop/FPGA_CNN_IP/FPGA_CNN_IP/FPGA_CNN_IP.srcs/sources_1/ip/conv1_bias1/conv1_bias1.xci
set_property used_in_implementation false [get_files -all c:/Users/Epoch/Desktop/FPGA_CNN_IP/FPGA_CNN_IP/FPGA_CNN_IP.srcs/sources_1/ip/conv1_bias1/conv1_bias1_ooc.xdc]

read_ip -quiet C:/Users/Epoch/Desktop/FPGA_CNN_IP/FPGA_CNN_IP/FPGA_CNN_IP.srcs/sources_1/ip/conv1_weight1/conv1_weight1.xci
set_property used_in_implementation false [get_files -all c:/Users/Epoch/Desktop/FPGA_CNN_IP/FPGA_CNN_IP/FPGA_CNN_IP.srcs/sources_1/ip/conv1_weight1/conv1_weight1_ooc.xdc]

read_ip -quiet C:/Users/Epoch/Desktop/FPGA_CNN_IP/FPGA_CNN_IP/FPGA_CNN_IP.srcs/sources_1/ip/conv1_weight2/conv1_weight2.xci
set_property used_in_implementation false [get_files -all c:/Users/Epoch/Desktop/FPGA_CNN_IP/FPGA_CNN_IP/FPGA_CNN_IP.srcs/sources_1/ip/conv1_weight2/conv1_weight2_ooc.xdc]

read_ip -quiet C:/Users/Epoch/Desktop/FPGA_CNN_IP/FPGA_CNN_IP/FPGA_CNN_IP.srcs/sources_1/ip/conv1_weight3/conv1_weight3.xci
set_property used_in_implementation false [get_files -all c:/Users/Epoch/Desktop/FPGA_CNN_IP/FPGA_CNN_IP/FPGA_CNN_IP.srcs/sources_1/ip/conv1_weight3/conv1_weight3_ooc.xdc]

read_ip -quiet C:/Users/Epoch/Desktop/FPGA_CNN_IP/FPGA_CNN_IP/FPGA_CNN_IP.srcs/sources_1/ip/conv1_weight4/conv1_weight4.xci
set_property used_in_implementation false [get_files -all c:/Users/Epoch/Desktop/FPGA_CNN_IP/FPGA_CNN_IP/FPGA_CNN_IP.srcs/sources_1/ip/conv1_weight4/conv1_weight4_ooc.xdc]

read_ip -quiet C:/Users/Epoch/Desktop/FPGA_CNN_IP/FPGA_CNN_IP/FPGA_CNN_IP.srcs/sources_1/ip/conv1_weight5/conv1_weight5.xci
set_property used_in_implementation false [get_files -all c:/Users/Epoch/Desktop/FPGA_CNN_IP/FPGA_CNN_IP/FPGA_CNN_IP.srcs/sources_1/ip/conv1_weight5/conv1_weight5_ooc.xdc]

read_ip -quiet C:/Users/Epoch/Desktop/FPGA_CNN_IP/FPGA_CNN_IP/FPGA_CNN_IP.srcs/sources_1/ip/conv1_weight6/conv1_weight6.xci
set_property used_in_implementation false [get_files -all c:/Users/Epoch/Desktop/FPGA_CNN_IP/FPGA_CNN_IP/FPGA_CNN_IP.srcs/sources_1/ip/conv1_weight6/conv1_weight6_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top cnn_struct -part xc7z020clg400-2


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef cnn_struct.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file cnn_struct_utilization_synth.rpt -pb cnn_struct_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
