# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: ip/weight_fc/weight_fc.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==weight_fc || ORIG_REF_NAME==weight_fc} -quiet] -quiet

# IP: ip/shift_ram_12/shift_ram_12.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==shift_ram_12 || ORIG_REF_NAME==shift_ram_12} -quiet] -quiet

# IP: ip/shift_ram_28/shift_ram_28.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==shift_ram_28 || ORIG_REF_NAME==shift_ram_28} -quiet] -quiet

# IP: ip/conv2_weight6/conv2_weight6.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==conv2_weight6 || ORIG_REF_NAME==conv2_weight6} -quiet] -quiet

# IP: ip/conv2_weight5/conv2_weight5.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==conv2_weight5 || ORIG_REF_NAME==conv2_weight5} -quiet] -quiet

# IP: ip/conv2_weight4/conv2_weight4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==conv2_weight4 || ORIG_REF_NAME==conv2_weight4} -quiet] -quiet

# IP: ip/conv2_weight3/conv2_weight3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==conv2_weight3 || ORIG_REF_NAME==conv2_weight3} -quiet] -quiet

# IP: ip/conv2_weight2/conv2_weight2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==conv2_weight2 || ORIG_REF_NAME==conv2_weight2} -quiet] -quiet

# IP: ip/conv2_weight1/conv2_weight1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==conv2_weight1 || ORIG_REF_NAME==conv2_weight1} -quiet] -quiet

# IP: ip/conv1_bias6/conv1_bias6.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==conv1_bias6 || ORIG_REF_NAME==conv1_bias6} -quiet] -quiet

# IP: ip/conv1_bias5/conv1_bias5.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==conv1_bias5 || ORIG_REF_NAME==conv1_bias5} -quiet] -quiet

# IP: ip/conv1_bias4/conv1_bias4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==conv1_bias4 || ORIG_REF_NAME==conv1_bias4} -quiet] -quiet

# IP: ip/conv1_bias3/conv1_bias3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==conv1_bias3 || ORIG_REF_NAME==conv1_bias3} -quiet] -quiet

# IP: ip/conv1_bias2/conv1_bias2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==conv1_bias2 || ORIG_REF_NAME==conv1_bias2} -quiet] -quiet

# IP: ip/conv1_bias1/conv1_bias1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==conv1_bias1 || ORIG_REF_NAME==conv1_bias1} -quiet] -quiet

# XDC: ip/weight_fc/weight_fc_ooc.xdc

# XDC: ip/conv2_weight6/conv2_weight6_ooc.xdc

# XDC: ip/conv2_weight5/conv2_weight5_ooc.xdc

# XDC: ip/conv2_weight4/conv2_weight4_ooc.xdc

# XDC: ip/conv2_weight3/conv2_weight3_ooc.xdc

# XDC: ip/conv2_weight2/conv2_weight2_ooc.xdc

# XDC: ip/conv2_weight1/conv2_weight1_ooc.xdc

# XDC: ip/conv1_bias6/conv1_bias6_ooc.xdc

# XDC: ip/conv1_bias5/conv1_bias5_ooc.xdc

# XDC: ip/conv1_bias4/conv1_bias4_ooc.xdc

# XDC: ip/conv1_bias3/conv1_bias3_ooc.xdc

# XDC: ip/conv1_bias2/conv1_bias2_ooc.xdc

# XDC: ip/conv1_bias1/conv1_bias1_ooc.xdc
