# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/Epoch/Desktop/FPGA_CNN_IP/FPGA_CNN_IP/FPGA_CNN_IP.srcs/sources_1/ip/image28x28/image28x28.xci
# IP: The module: 'image28x28' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Epoch/Desktop/FPGA_CNN_IP/FPGA_CNN_IP/FPGA_CNN_IP.srcs/sources_1/ip/image28x28/image28x28_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'image28x28'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: c:/Users/Epoch/Desktop/FPGA_CNN_IP/FPGA_CNN_IP/FPGA_CNN_IP.srcs/sources_1/ip/image28x28/image28x28.xci
# IP: The module: 'image28x28' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Epoch/Desktop/FPGA_CNN_IP/FPGA_CNN_IP/FPGA_CNN_IP.srcs/sources_1/ip/image28x28/image28x28_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'image28x28'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
