# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/Epoch/Desktop/FPGA_CNN_IP/FPGA_CNN_IP/FPGA_CNN_IP.srcs/sources_1/ip/conv1_weight6/conv1_weight6.xci
# IP: The module: 'conv1_weight6' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Epoch/Desktop/FPGA_CNN_IP/FPGA_CNN_IP/FPGA_CNN_IP.srcs/sources_1/ip/conv1_weight6/conv1_weight6_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'conv1_weight6'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: c:/Users/Epoch/Desktop/FPGA_CNN_IP/FPGA_CNN_IP/FPGA_CNN_IP.srcs/sources_1/ip/conv1_weight6/conv1_weight6.xci
# IP: The module: 'conv1_weight6' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Epoch/Desktop/FPGA_CNN_IP/FPGA_CNN_IP/FPGA_CNN_IP.srcs/sources_1/ip/conv1_weight6/conv1_weight6_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'conv1_weight6'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
